version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "src/Garage.Web/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "src/Garage.Web/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: "gomod"
    directory: "src/Garage.FeatureFlags/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
